# Generated by Django 5.0.9 on 2026-03-09 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ActivityProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(max_length=64)),
                ('step_index', models.PositiveIntegerField(default=0)),
                ('step_count', models.PositiveIntegerField(default=0)),
                ('is_complete', models.BooleanField(default=False)),
                ('completed_checks', models.JSONField(blank=True, default=list)),
                ('inputs', models.JSONField(blank=True, default=dict)),
                ('show_worked_example', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'activity_key'),
                'indexes': [models.Index(fields=['activity_key'], name='core_activi_activit_a671b9_idx'), models.Index(fields=['is_complete'], name='core_activi_is_comp_c9512f_idx')],
                'unique_together': {('user', 'activity_key')},
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='core.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('classroom_id', 'student_id'),
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.CreateModel(
            name='HintAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_key', models.CharField(max_length=64)),
                ('checkpoint_id', models.CharField(max_length=128)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('shown_level', models.PositiveSmallIntegerField(default=0)),
                ('show_count', models.PositiveIntegerField(default=0)),
                ('reveal_count', models.PositiveIntegerField(default=0)),
                ('revealed_worked', models.BooleanField(default=False)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hint_analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user_id', 'activity_key', 'checkpoint_id'),
                'indexes': [models.Index(fields=['activity_key', 'checkpoint_id'], name='core_hintan_activit_0084f1_idx'), models.Index(fields=['show_count', 'reveal_count'], name='core_hintan_show_co_70839e_idx')],
                'unique_together': {('user', 'activity_key', 'checkpoint_id')},
            },
        ),
    ]
